### ISSUE TITLE
I am getting 0 precision during retinanet-evaluate in TrainOCR

### ISSUE THREAD

**Issue by munitech4u** [ferrygun/PDFTableExtract#2]
Hi,

I downloaded some receipts from internet and manually labeled and created annotations. Everything seems to be going as per plan, until I noticed 0 precision while evaluating retina-net output weight file:

![0_precision_training](https://user-images.githubusercontent.com/7777086/92087489-2c066180-ede9-11ea-8a37-d555891ce2c1.jpg)

I can see for you precision is about .83. What might be wrong?

**Comment by CaptainStabs** [comment]
@munitech4u Do you still have RN2 on your system?
